name: Greetings # Name of the workflow, it's optional
# Events are described in the 'on' container. It is required.
on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting: # Job name
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "You have created your first issue! 🎉"
        pr-message: "Congrats on your first pull request! 🎉"
